data(npk)
print(npk)
wynik_anova1 <- aov(yield ~ factor(N), data = npk)
wynik_anova2 <- aov(yield ~ factor(P), data = npk)
wynik_anova3 <- aov(yield ~ factor(K), data = npk)
summary(wynik_anova1)
summary(wynik_anova2)
summary(wynik_anova3)
wynik_anova4 <- aov(yield ~ factor(block), data = npk)
summary(wynik_anova4)
TukeyHSD(wynik_anova1)
TukeyHSD(wynik_anova2)
TukeyHSD(wynik_anova3)
kruskal.test(yield ~ factor(N), data = npk)
kruskal.test(yield ~ factor(P), data = npk)
kruskal.test(yield ~ factor(K), data = npk)
model_lm1 <- lm(yield ~ factor(N), data = npk)
model_lm2 <- lm(yield ~ factor(P), data = npk)
model_lm3 <- lm(yield ~ factor(K), data = npk)
summary(model_lm1)
summary(model_lm2)
summary(model_lm3)
model_multi <- lm(yield ~ factor(N) + factor(P) + factor(K) + factor(block), data = npk)
summary(model_multi)
